### ISSUE TITLE
Build without error but I cannot find the file "depth2X" 

### ISSUE THREAD

**Issue by ChaofanWu-2336** [JonasToth/depth-conversions#1]
When I build the project with "Build with system libraries" referred by the file "compilation.md"，It builded without error,but there is no any executable file in build dir.  What is wrong?

**Comment by rlsch** [comment]
Assuming your build dir is called "build", the file shoud be here:
build/src/apps/depth2x

**Comment by JonasToth** [comment]
Hey @XiaoMing2336 , sorry for not reacting to the issue. It got lost in all my github notifications.
I added a short sentence in the documentation, hopefully it works for you?

And thanks @rlsch for reacting to the issue :)
